config-version: 2
models:
  hubspot:
    +materialized: table
    marketing:
      intermediate:
        +materialized: ephemeral
name: hubspot
require-dbt-version:
- '>=0.18.0'
- <0.19.0
vars:
  hubspot:
    company: '{{ ref(''stg_hubspot__company'') }}'
    company_property_history: '{{ ref(''stg_hubspot__company_property_history'') }}'
    contact: '{{ ref(''stg_hubspot__contact'') }}'
    contact_list: '{{ ref(''stg_hubspot__contact_list'') }}'
    contact_list_member: '{{ ref(''stg_hubspot__contact_list_member'') }}'
    contact_property_history: '{{ ref(''stg_hubspot__contact_property_history'') }}'
    deal: '{{ ref(''stg_hubspot__deal'') }}'
    deal_pipeline: '{{ ref(''stg_hubspot__deal_pipeline'') }}'
    deal_pipeline_stage: '{{ ref(''stg_hubspot__deal_pipeline_stage'') }}'
    deal_property_history: '{{ ref(''stg_hubspot__deal_property_history'') }}'
    email_event: '{{ ref(''stg_hubspot__email_event'') }}'
    email_event_bounce: '{{ ref(''stg_hubspot__email_event_bounce'') }}'
    email_event_click: '{{ ref(''stg_hubspot__email_event_click'') }}'
    email_event_deferred: '{{ ref(''stg_hubspot__email_event_deferred'') }}'
    email_event_delivered: '{{ ref(''stg_hubspot__email_event_delivered'') }}'
    email_event_dropped: '{{ ref(''stg_hubspot__email_event_dropped'') }}'
    email_event_forward: '{{ ref(''stg_hubspot__email_event_forward'') }}'
    email_event_open: '{{ ref(''stg_hubspot__email_event_open'') }}'
    email_event_print: '{{ ref(''stg_hubspot__email_event_print'') }}'
    email_event_sent: '{{ ref(''stg_hubspot__email_event_sent'') }}'
    email_event_spam_report: '{{ ref(''stg_hubspot__email_event_spam_report'') }}'
    email_event_status_change: '{{ ref(''stg_hubspot__email_event_status_change'')
      }}'
    email_metrics:
    - bounces
    - clicks
    - deferrals
    - deliveries
    - drops
    - forwards
    - opens
    - prints
    - spam_reports
    - unsubscribes
    engagement: '{{ ref(''stg_hubspot__engagement'') }}'
    engagement_call: '{{ ref(''stg_hubspot__engagement_call'') }}'
    engagement_company: '{{ ref(''stg_hubspot__engagement_company'') }}'
    engagement_contact: '{{ ref(''stg_hubspot__engagement_contact'') }}'
    engagement_deal: '{{ ref(''stg_hubspot__engagement_deal'') }}'
    engagement_email: '{{ ref(''stg_hubspot__engagement_email'') }}'
    engagement_email_cc: '{{ ref(''stg_hubspot__engagement_email_cc'') }}'
    engagement_email_to: '{{ ref(''stg_hubspot__engagement_email_to'') }}'
    engagement_meeting: '{{ ref(''stg_hubspot__engagement_meeting'') }}'
    engagement_note: '{{ ref(''stg_hubspot__engagement_note'') }}'
    engagement_task: '{{ ref(''stg_hubspot__engagement_task'') }}'
    owner: '{{ ref(''stg_hubspot__owner'') }}'
version: 1.0.0
